@extends('cms.layouts.app')
@section('title', 'Analitik Pengunjung')
@section('content')
<div class="actions" style="margin-bottom:20px"><span>Periode:</span>@foreach([7,30,90] as $range)<a class="btn btn-small {{ $days===$range ? 'btn-primary' : 'btn-secondary' }}" href="{{ route('cms.analytics',['days'=>$range]) }}">{{ $range }} hari</a>@endforeach</div>
<div class="stat-grid"><div class="stat-card"><span>Page views</span><strong>{{ number_format($stats['views']) }}</strong></div><div class="stat-card"><span>Pengunjung unik</span><strong>{{ number_format($stats['visitors']) }}</strong></div><div class="stat-card"><span>Hari ini</span><strong>{{ number_format($stats['today']) }}</strong></div><div class="stat-card"><span>Rata-rata / hari</span><strong>{{ number_format($stats['avg'],1) }}</strong></div></div>
<section class="card"><div class="card-header"><h2>Tren Kunjungan</h2></div><div class="card-body"><div class="chart-scroll"><div class="chart">@php($max=max(1,$daily->max()))@foreach($daily as $date=>$count)<div class="chart-col" title="{{ $date }}: {{ $count }} kunjungan"><div class="chart-bar" style="height:{{ max(2,round($count/$max*180)) }}px"></div><span class="chart-label">{{ \Carbon\Carbon::parse($date)->format('d/m') }}</span></div>@endforeach</div></div></div></section>
<div class="two-col"><section class="card"><div class="card-header"><h2>Bagian paling sering dilihat</h2></div><div class="card-body"><ol class="rank-list">@forelse($topSections as $section=>$count)<li><span>#{{ $section }}</span><b>{{ number_format($count) }}</b></li>@empty<li>Belum ada data interaksi.</li>@endforelse</ol></div></section>
<section class="card"><div class="card-header"><h2>Sumber kunjungan</h2></div><div class="card-body"><ol class="rank-list">@forelse($topReferrers as $referrer=>$count)<li><span>{{ $referrer }}</span><b>{{ number_format($count) }}</b></li>@empty<li>Belum ada data kunjungan.</li>@endforelse</ol></div></section></div>
<section class="card"><div class="card-header"><h2>Browser</h2></div><div class="card-body"><ol class="rank-list">@forelse($browsers as $browser=>$count)<li><span>{{ $browser }}</span><b>{{ number_format($count) }}</b></li>@empty<li>Belum ada data.</li>@endforelse</ol></div></section>
@endsection
